@startuml
'https://plantuml.com/sequence-diagram

autonumber
'Gana Jugador 1'
Actor Jugador

Jugador -> "china:Pais": AtacarA(Katchatka:Pais)

"china:Pais"-> "china:Pais": puedeAtacarA(Katchatka:Pais)
return true

"china:Pais" -> ":Batalla":batallaEntre(china:Pais, katchatka:Pais)

":Batalla" -> "china:Pais": ocuparA(Katchatka:Pais)

":Batalla" -> "katchatka:Pais": tirarDadosDefensivos()
return dadosDefensivos

":Batalla" -> "china:Pais": tirarDadosAtacantes()
    "china:Pais" -> "ejercitos:Ejercitos": tirarDadosAtacantes()
    return dadosAtacantes
"china:Pais" --> ":Batalla": dadosAtacantes

":Batalla" -> "dadosDefensivos:Dados": batallarContra(dadosAtacantes)
return resultadoDefensa

":Batalla" -> "katchatka:Pais": contabilizarBajas(resultadoDefensa)

":Batalla" -> "dadosAtacantes:Dados": batallarContra(dadosDefensivos)
return resultadoAtaque

":Batalla" -> "china:Pais": contabilizarBajas(resultadoAtaque)

"china:Pais" -> "katchatka:Pais": mandarTropasA(:Ejercito)

@enduml