@startuml

Actor testCase

autonumber
"testCase" -> "jugador1:Jugador": ocupa(argentina:Pais)
    "jugador1:Jugador" -> "argentina:Pais": recibirTropas(reservasArgentina:Ejercitos)

"testCase" -> "jugador2:Jugador": ocupa(chile:Pais)
    "jugador2:Jugador" -> "chile:Pais": recibirTropas(reservasChile:Ejercitos)

"testCase" -> "jugador1:Jugador": atacarA(chile:Pais)
    "jugador1:Jugador" -> "argentina:Pais": atacarA(chile:Pais)
        "argentina:Pais" -> "chile:Pais": recibirTropas(reservasArgentina:Ejercitos)

"testCase" -> "jugador2:Jugador": tieneFuerzasEn(chile)

@enduml