@startuml
'https://plantuml.com/sequence-diagram

autonumber
'Gana Jugador 1'
Actor Jugador
Jugador -> Jugador: AtacarPaisDesdeA(Kamchatka, china)

Jugador -> "kamchatka:Pais": AtacarA(china:Pais)

"kamchatka:Pais" -> ":Batalla": atacar(katchatka:Ejercito, china:Ejercito)

":Batalla" -> "dadosAtacante:Dados" **:<<new()>>
":Batalla" -> "dadosDefensor:Dados" **:<<new()>>

":Batalla" -> "dadosAtacante:Dados": tirarDados(cantidadAtacante)
return resultadoDadosAtacante

":Batalla" -> "dadosDefensor:Dados": tirarDados(cantidadDefensor)
return resultadoDadosDefensor

":Batalla" -> ":Batalla" : compararResultados(resultadoAtacante, resultadoDefensor)
return resultadoBatalla

":Batalla" -> "kamchatka:Ejercito" : restarEjercitos(resultadoBatalla[0])

":Batalla" -> "china:Ejercito" : restarEjercitos(resultadoBatalla[1])


"kamchatka:Pais" ->"china:Pais" :recibirTropas(kamchatcka:Pais)
"china:Pais" -> "china:Ejercito": disputarDominioDe(Pais, kamchatkaEjercito:Ejercito)

return Ejercitos con el comandante cambiado
@enduml