@startuml
'https://plantuml.com/sequence-diagram

autonumber
'Gana Jugador 1'
Actor Jugador

Jugador -> "china:Pais": AtacarA(Katchatka:Pais)
"china:Pais" -> ":Batalla":batallaEntre(chinaEjercito:Ejercito, katchatkaEjercito:Ejercito)

":Batalla" -> "dadosAtacante:Dados" **:<<new()>>

loop max3 min1 teniendo en cuenta la cantidad de ejercito

":Batalla" -> "dadosAtacante:Dados": tirarDados()
return int

end

":Batalla" -> "dadosDefensor:Dados" **:<<new()>>

loop max3 min1

":Batalla" -> "dadosDefensor:Dados": tirarDados()
return int

end

":Batalla" -> ":Batalla" : resultadoBatalla(atacante, defensor)
return perdidaAtacante

":Batalla" -> "chinaEjercito:Ejercito":restarEjercito(perdidaAtacante:int)


":Batalla" -> ":Batalla" : resultadoBatalla(defensor, atacante)
return perdidaDefensor

":Batalla" -> "kactchatkaEjercito:Ejercito":restarEjercito(perdidaDefensor:int)
"kactchatkaEjercito:Ejercito" -> "derrotado:EstadoDelEjercito" **:new()
return EstadoDelEjercito

"china:Pais" -> "katctchatka:Pais": recibirEjercitos(chinaEjercito)
"katctchatka:Pais" -> "kactchatkaEjercito:Ejercito": disputarDominioDe(katchatka, chinaEjercito)
"kactchatkaEjercito:Ejercito" -> "derrotado:EstadoDelEjercito": estaDerrotado()
return true
"kactchatkaEjercito:Ejercito" --> "katctchatka:Pais": chinaEjercito


@enduml