@startuml
'https://plantuml.com/class-diagram

class Juego{
-primerJugador:Jugador
+accionDeJugador(unJugador:Jugador):void
}

class Jugador{
-numeroDeJugador:int
-siguienteJugador:Jugador
+atacarA(unPais:Pais):void
+moverEjercidoDeA(unPais:Pais, unPais:Pais):void
+colocarEjercitoEn(unPais:Pais):void
}

class Ejercitos{
-numeroDeEjercitos:int
+tirarDados():Dados
+agregarEjercitos(cantidad:int):void
}


class Pais{
-nombreDelPais:String
-numeroDeJugador:int
-PaisesConectados:Array<Pais>
+agregarEjercito(cantidad:int):void
+atacarA(otroPais:Pais)
+PuedoAtacarA(Pais):boolean
}


class ObjetivoJugador{
-objetivoComun: Ocupacion30Paises
}

class Dados{
-cantidad:int
+ordenar():void
+lanzar():int
+perdidaDeFichasContra(otrosDados:Dados):int
}

class Continente{
-paises:Paises
+ estaOcupadoPor(numeroDeJugador:int): boolean
}

interface FaseDeRonda{
+{abstract} accionDeJugador(unJugador:Jugador):void
}

interface Objetivo{
+ estaCumplido(): boolean
}


class Atacar{
+accionDeJugador(unJugador:Jugador):void
}

class Reagrupar{
+accionDeJugador(unJugador:Jugador):void
}

class ColocarEjercitos{
+accionDeJugador(unJugador:Jugador):void
}

class Batalla{
+batallaEntre(ejercitoAtacante:Ejercitos, ejercitoDefensor: Ejercitos)
}

Juego ---->"6" Jugador
Juego --> FaseDeRonda

FaseDeRonda <|.. Atacar
FaseDeRonda <|.. Reagrupar
FaseDeRonda <|.. ColocarEjercitos


Jugador --> Pais
Jugador --> Objetivo
Jugador --> Continente

Pais --> "1..*"Ejercitos

Objetivo <|.. Ocupacion
Objetivo <|.. Destruccion
Objetivo <-- ObjetivoJugador
Objetivo <|.. ObjetivoJugador

ObjetivoJugador --> Ocupacion

Pais ..> Batalla
Ejercitos ..> Dados
Batalla ..> Dados

Continente --> "1..*" Pais

@enduml