@startuml
'https://plantuml.com/class-diagram

class Juego{
-primerJugador:Jugador
+accionDeJugador(unJugador:Jugador):void
}

class Jugador{
-numeroDeJugador:int
-siguienteJugador:Jugador
+atacarA(unPais:Pais):void
+moverEjercidoDeA(unPais:Pais, unPais:Pais):void
+colocarEjercitoEn(unPais:Pais):void
}

class Ejercitos{

+tirarDados():Dados
+agregarEjercitos(cantidad:int):void
+restarEjercito(cantidad:int):void
}

interface EstadoEjercitos{

 + evaluarFuerzasRestantes(): EstadoEjercitos
 + getCantidadFuerzas(): int
 + agregarFuerzas(int numeroDeFuerzas): EstadoEjercitos
 + restarFuerzas(int numeroFuerzas): EstadoEjercitos
 + estanDerrotados(): boolean
}

class EnPie{
-numeroDeEjercitos:int
}
class Derrotados{
}

class Pais{
-nombreDelPais:String
-PaisesConectados:Array<Pais>
+agregarEjercito(cantidad:int):void
+restarEjercito(cantidad:int):void
+atacarA(otroPais:Pais)
}


class ObjetivoJugador{
-objetivoComun: Ocupacion30Paises
}

class Dados{
-cantidad:int
-ordenar():void
+tirarDados():int
+compararContra(otrosDados:Dados):int
}

class Continente{
-paises:Paises
+ estaOcupadoPor(numeroDeJugador:int): boolean
}

interface FaseDeRonda{
+{abstract} accionDeJugador(unJugador:Jugador):void
}

interface Objetivo{
+ estaCumplido(): boolean
}


class Atacar{
+accionDeJugador(unJugador:Jugador):void
}

class Reagrupar{
+accionDeJugador(unJugador:Jugador):void
}

class ColocarEjercitos{
+accionDeJugador(unJugador:Jugador):void
}

class Batalla{
+batallaEntre(ejercitoAtacante:Ejercitos, ejercitoDefensor: Ejercitos)
}

Juego ---->"6" Jugador
Juego --> FaseDeRonda

FaseDeRonda <|.. Atacar
FaseDeRonda <|.. Reagrupar
FaseDeRonda <|.. ColocarEjercitos


Jugador --> Pais
Jugador --> Objetivo
Jugador --> Continente

Pais --> Ejercitos

Objetivo <|.. Ocupacion
Objetivo <|.. Destruccion
Objetivo <-- ObjetivoJugador
Objetivo <|.. ObjetivoJugador

ObjetivoJugador --> Ocupacion

Ejercitos ..> Batalla
Ejercitos ..> Dados
Ejercitos -> "comandante" Jugador
EstadoEjercitos <- Ejercitos
EstadoEjercitos <|.. EnPie
EstadoEjercitos <|.. Derrotados
Batalla ..> Dados

Continente --> "1..*" Pais

@enduml