@startuml

Actor testCase

autonumber
"testCase" -> "jugador1:Jugador": ocupar(argentina)
"jugador1:Jugador" -> "argentina:Pais": recibirFuerzas(ejercitosExtranjeros:Ejercitos)
"argentina:Pais" -> "ejercitosArgentinos:Ejercitos": estanDerrotados()
return true
"argentina:Pais" -> "ejercitosArgentinos:Ejercitos": debenDesocupar(argentina)
"ejercitosArgentinos:Ejercitos" -> "jugador2:Jugador": perdisteA(argentina)
"ejercitosArgentinos:Ejercitos" --> "argentina:Pais": true

"argentina:Pais" -> "ejercitosExtranjeros:Ejercitos": ocupacionExitosaDe(argentina)



@enduml