@startuml

class Jugador{

    + atacarA(unPais:Pais):void
    + ocupa(unPais:Pais):void

}

class Pais{
    + atacarA(otroPais:Pais):void
    + estaOcupadoPor(unJugador:Jugador):boolean
    + recibirTropas(tropas:Ejercitos):void
    + estaOcupadoPor(unJugador:Jugador):boolean


}

class Ejercitos{
    + estanBajoElMandoDe(unJugador:Jugador):boolean

}

Jugador -> Pais:"paisesOcupados"
Jugador -> Ejercitos: "resevas"
Pais -> Ejercitos:"fuerzasOcupantes"
Ejercitos -> Jugador




@enduml